name: On Release

on:
  release:
    types: [created]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Output
        uses: actions/checkout@v2
      - run: echo ${{ github.event.release.tag_name }}
